# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(default=0)),
                ('name', models.TextField()),
                ('status', models.CharField(choices=[('ENABLED', 'ENABLED'), ('OFFLINE', 'OFFLINE')], max_length=15)),
                ('campaign_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField(default=0)),
                ('name', models.TextField()),
                ('status', models.CharField(choices=[('PAUSED', 'PAUSED'), ('ON', 'ON')], max_length=15)),
                ('budget', models.IntegerField(default=0)),
                ('advertising_channel_type', models.CharField(choices=[('SEARCH', 'SEARCH'), ('DISPLAY', 'DISPLAY')], max_length=15)),
            ],
        ),
    ]
