# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expanded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xsi_type', models.TextField()),
                ('ad_group_id', models.IntegerField(default=0)),
                ('headline_part1', models.CharField(max_length=15)),
                ('headline_part2', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('path1', models.TextField()),
                ('path2', models.TextField()),
            ],
        ),
    ]
