# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expanded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroups',
            name='_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='expanded',
            name='ad_group_id',
            field=models.IntegerField(default=1),
        ),
    ]
